security:
    encoders:
        Maba\Bundle\OAuthCommerceAccountsBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_OAUTH_APPLICATION: ROLE_API
        ROLE_OAUTH_CLIENT: ROLE_API
        IS_AUTHENTICATED_ANONYMOUSLY: ROLE_ANY
        ROLE_USER: ROLE_ANY
        ROLE_API: ROLE_ANY
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        users:
            entity: { class: MabaOAuthCommerceAccountsBundle:User, property: username }
        clients:
            entity: { class: MabaOAuthCommerceCommonBundle:Client, property: id }
        applications:
            entity: { class: MabaOAuthCommerceCommonBundle:Application, property: id }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            stateless: true
            provider: clients
            pattern: ^/api/
            oauth_commerce_proxy:
                application_user_provider: applications
                secret: %maba_oauth_commerce_proxy.header_signature_secret%
        user:
            pattern: ^/
            anonymous: ~
            provider: users
            form_login:
                login_path:  login
                check_path:  login_check
                use_forward: true
                csrf_parameter:       _token
                csrf_provider:        form.csrf_provider
                use_referer: true
                intention:            login
                failure_handler: maba_oauth_commerce_accounts.login_failure_handler
            logout:
                path:   logout
                target: /
                invalidate_session: true
                csrf_parameter:       _token
                csrf_provider:        form.csrf_provider
                intention:            logout


    access_control:
        -
            path: ^/$
            role: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/login$
            role: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/confirm$
            role: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/certificate$
            role: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/api
            role: ROLE_API
        -
            path: ^/
            role: ROLE_USER
